---
- name: Systemd - Ensure service script is present.
  become: true
  template:
    src:  "haproxy.systemd.j2"
    dest: "/lib/systemd/system/haproxy.service"
    owner: root
    group: root
    mode: 0755
  notify: restart haproxy

- name: Systemd - Ensure service is linked into /etc/systemd.
  file:
    src: "/lib/systemd/system/haproxy.service"
    dest: "/etc/systemd/system/multi-user.target.wants/haproxy.service"
    state: link
